
(function(){'use strict';
function activate(id,push){var p=document.getElementById(id);if(!p)return;document.querySelectorAll('.side .navbtn[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===id);b.classList.remove('fj-v617-active')});document.querySelectorAll('.panel').forEach(function(x){x.classList.toggle('active',x.id===id)});try{localStorage.setItem('fj_active_panel_v20',id)}catch(e){}if(id==='adminAccess'&&typeof window.loadAdminAccess==='function'){try{window.loadAdminAccess()}catch(e){}}if(push){try{history.pushState({fjApp:true,fjPanel:id},'',location.href)}catch(e){}}}
function bind(){if(document.documentElement.dataset.fjV104Nav==='1')return;document.documentElement.dataset.fjV104Nav='1';document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('.side .navbtn[data-tab]'):null;if(!b)return;var id=b.dataset.tab;if(!document.getElementById(id))return;ev.preventDefault();ev.stopImmediatePropagation();activate(id,true)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();

/* PERSONAL TRAINER COMPARISON — PT packages only. */
const PTCMP_LEVELS=['Smart Coach','Advance Coach','Pro Coach','Master Coach'];
function ptcmpData(){return typeof PT_SALES_CATALOG!=='undefined'?PT_SALES_CATALOG:{'Smart Coach':{REGULAR:smartReg,BUNDLING:smartBund,RENEWAL:smartReg},'Advance Coach':{REGULAR:advancedReg,BUNDLING:advancedBund,RENEWAL:advancedReg},'Pro Coach':{REGULAR:proCoach,BUNDLING:null,RENEWAL:proCoach},'Master Coach':{REGULAR:masterCoach,BUNDLING:null,RENEWAL:masterCoach}}}
function ptcmpModeData(level,mode){const d=ptcmpData()[level]||{};if(mode==='RENEWAL')return d.BUNDLING&&d.BUNDLING.length?d.BUNDLING:(d.RENEWAL||d.REGULAR||[]);return d.REGULAR||[]}
function ptcmpEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ptcmpMoney(n){return typeof money==='function'?money(Number(n)||0):'Rp '+(Number(n)||0).toLocaleString('id-ID')}
function ptcmpCount(){return Math.min(3,Math.max(2,Number(document.getElementById('ptcmpCount')?.value||3)))}
function ptcmpBuild(){const root=document.getElementById('ptcmpSelectors');if(!root)return;const count=ptcmpCount(),filter=document.getElementById('ptcmpFilter')?.value||'all',levels=filter==='all'?PTCMP_LEVELS:[filter];root.innerHTML=Array.from({length:count},(_,i)=>`<div class="ptcmp-package-card"><h3>Paket ${i+1}</h3><div class="field"><label>Coach</label><select id="ptcmpLevel${i}" onchange="ptcmpPackages(${i})">${levels.map(x=>`<option>${ptcmpEsc(x)}</option>`).join('')}</select></div><div class="field"><label>Mode Harga</label><select id="ptcmpMode${i}" onchange="ptcmpPackages(${i})"><option value="REGULAR">Regular</option><option value="RENEWAL">Renewal</option></select></div><div class="field"><label>Paket PT</label><select id="ptcmpPackage${i}" onchange="ptcmpUpdateAuto(${i})"></select></div><div class="field"><label>Cashback Automatic PT</label><div id="ptcmpAuto${i}" class="ptcmp-auto-cashback">Rp 0</div></div><div class="field"><label>Cashback Manual (Rp)</label><input id="ptcmpManual${i}" type="number" min="0" value="0" inputmode="numeric" oninput="ptcmpRenderIfReady()"></div><div class="field"><label>Merchandise</label><select id="ptcmpMerch${i}" onchange="ptcmpRenderIfReady()"><option value="none">Tidak ada</option><option>Merchandise</option><option>Gym Bag</option><option>Shoe Bag</option></select></div><div class="field"><label>Manager Approval</label><button type="button" class="btn alt" id="ptcmpApproval${i}" data-approved="0" onclick="ptcmpToggleApproval(${i})">APPROVAL MANAGER</button></div></div>`).join('');for(let i=0;i<count;i++)ptcmpPackages(i)}
function ptcmpPackages(i){const level=document.getElementById('ptcmpLevel'+i)?.value,mode=document.getElementById('ptcmpMode'+i)?.value,sel=document.getElementById('ptcmpPackage'+i);if(!sel)return;const arr=ptcmpModeData(level,mode);sel.innerHTML=arr.length?arr.map((p,j)=>`<option value="${j}">${ptcmpEsc(p[0])} • ${p[1]} sesi • ${ptcmpMoney(p[3])}</option>`).join(''):'<option value="">Tidak tersedia</option>';ptcmpUpdateAuto(i)}
function ptcmpUpdateAuto(i){const level=document.getElementById('ptcmpLevel'+i)?.value,mode=document.getElementById('ptcmpMode'+i)?.value,idx=Number(document.getElementById('ptcmpPackage'+i)?.value||0),p=ptcmpModeData(level,mode)[idx],el=document.getElementById('ptcmpAuto'+i);if(el)el.textContent=ptcmpMoney(Number(p?.[6]||0));ptcmpRenderIfReady()}
function ptcmpToggleApproval(i){const b=document.getElementById('ptcmpApproval'+i);if(!b)return;b.dataset.approved=b.dataset.approved==='1'?'0':'1';b.textContent=b.dataset.approved==='1'?'✓ MANAGER APPROVED':'APPROVAL MANAGER';b.classList.toggle('green',b.dataset.approved==='1');ptcmpRenderIfReady()}
function ptcmpSelected(){const out=[];for(let i=0;i<ptcmpCount();i++){const level=document.getElementById('ptcmpLevel'+i)?.value,mode=document.getElementById('ptcmpMode'+i)?.value,idx=Number(document.getElementById('ptcmpPackage'+i)?.value||0),p=ptcmpModeData(level,mode)[idx];if(!p)return null;const manual=Math.max(0,Number(document.getElementById('ptcmpManual'+i)?.value||0)),price=Number(p[3])||0,auto=Number(p[6])||0,merch=document.getElementById('ptcmpMerch'+i)?.value||'none',approval=document.getElementById('ptcmpApproval'+i)?.dataset.approved==='1';out.push({slot:i+1,level,mode,code:p[0],sessions:Number(p[1])||0,validity:p[2]||'—',price,perSession:Number(p[4])||price/(Number(p[1])||1),points:Number(p[5])||0,auto,manual,merch,approval,final:Math.max(0,price-manual),totalCashback:auto+manual})}return out}
function ptcmpRows(ps){const rows=[['Level Coach',p=>p.level,''],['Mode Harga',p=>p.mode,''],['Kode Paket PT',p=>p.code,''],['Jumlah Sesi',p=>p.sessions+' sesi',''],['Masa Berlaku',p=>p.validity,''],['Harga Paket PT',p=>ptcmpMoney(p.price),'sum-price'],['Harga per Sesi',p=>ptcmpMoney(p.perSession),'sum-price'],['Cashback Automatic PT — Masuk Akun',p=>ptcmpMoney(p.auto),'cashback-auto'],['Cashback Manual — Potongan Harga',p=>ptcmpMoney(p.manual),'cashback-manual'],['Harga Setelah Potongan Manual',p=>ptcmpMoney(p.final),'sum-final']];if(ps.some(p=>p.merch&&p.merch!=='none'))rows.push(['Merchandise',p=>p.merch==='none'?'Tidak ada':p.merch,'']);rows.push(['Manager Approval',p=>p.approval?'✓ Approved':'Belum approved','']);return rows}
function ptcmpRender(){const root=document.getElementById('ptcmpResult'),ps=ptcmpSelected();if(!root)return;if(!ps){root.innerHTML='<div class="notice warn">Pilih paket PT yang tersedia untuk semua kolom.</div>';return}const rows=ptcmpRows(ps);root.innerHTML=`<div class="ptcmp-cashback-note"><b>Perbedaan Cashback:</b> <span class="ptcmp-auto-note">Cashback Automatic PT masuk ke akun dan tidak mengurangi harga paket.</span> <span class="ptcmp-manual-note">Cashback Manual saja yang menjadi potongan harga.</span></div><table class="ptcmp-compare-table"><thead><tr><th>Detail Paket PT</th>${ps.map(p=>`<th>Paket ${p.slot}<br>${ptcmpEsc(p.level)}<br>${ptcmpEsc(p.code)}</th>`).join('')}</tr></thead><tbody>${rows.map(([label,fn,cls])=>`<tr class="${cls}"><td>${ptcmpEsc(label)}</td>${ps.map(p=>`<td>${label==='Harga Paket PT'?`<span class="ptcmp-emphasis">${ptcmpEsc(fn(p))}</span>`:label==='Harga Setelah Cashback Manual'?`<span class="ptcmp-final">${ptcmpEsc(fn(p))}</span>`:ptcmpEsc(fn(p))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function ptcmpRenderIfReady(){const r=document.getElementById('ptcmpResult');if(r&&!r.querySelector('.ptcmp-empty')&&r.querySelector('table'))ptcmpRender()}
function ptcmpSummaryRows(ps){return ptcmpRows(ps).map(([label,fn,cls])=>`<tr class="${cls}"><td>${ptcmpEsc(label)}</td>${ps.map(p=>`<td>${ptcmpEsc(fn(p))}</td>`).join('')}</tr>`).join('')}
function ptcmpShowSummary(){const ps=ptcmpSelected();if(!ps){alert('Pilih paket PT untuk semua kolom terlebih dahulu.');return}const modal=document.getElementById('ptcmpSummaryModal'),content=document.getElementById('ptcmpSummaryContent');if(!modal||!content)return;content.innerHTML=`<div class="ptcmp-cashback-note"><b>Perbedaan Cashback:</b> <span class="ptcmp-auto-note">Automatic PT masuk ke akun, tidak mengurangi harga.</span> <span class="ptcmp-manual-note">Hanya Cashback Manual yang memotong harga.</span></div><table class="ptcmp-summary-table"><thead><tr><th>Keterangan</th>${ps.map(p=>`<th>Paket ${p.slot}<br><span>${ptcmpEsc(p.level)}</span><br><small>${ptcmpEsc(p.code)}</small></th>`).join('')}</tr></thead><tbody>${ptcmpSummaryRows(ps)}</tbody></table>`;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('ptcmp-summary-open')}
function ptcmpCloseSummary(){const m=document.getElementById('ptcmpSummaryModal');if(!m)return;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('ptcmp-summary-open')}
function ptcmpReset(){const count=document.getElementById('ptcmpCount');if(count)count.value='3';const filter=document.getElementById('ptcmpFilter');if(filter)filter.value='all';ptcmpBuild();const r=document.getElementById('ptcmpResult');if(r)r.innerHTML='<div class="ptcmp-empty">Pilih paket yang ingin dibandingkan, lalu klik Compare.</div>';ptcmpCloseSummary()}
function ptcmpSave(){const ps=ptcmpSelected();if(!ps){alert('Pilih paket PT terlebih dahulu.');return}const blob=new Blob([JSON.stringify({title:'Personal Trainer Comparison',createdAt:new Date().toISOString(),packages:ps},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='personal-trainer-comparison.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function ptcmpPrint(){const ps=ptcmpSelected();if(!ps){alert('Pilih paket PT untuk semua kolom sebelum print.');return}const old=document.querySelector('.ptcmp-print-root');if(old)old.remove();const root=document.createElement('div');root.className='ptcmp-print-root';const rows=ptcmpRows(ps),full=`<table><thead><tr><th>Detail Paket PT</th>${ps.map(p=>`<th>Paket ${p.slot}<br>${ptcmpEsc(p.level)}<br>${ptcmpEsc(p.code)}</th>`).join('')}</tr></thead><tbody>${rows.map(([label,fn])=>`<tr><td><b>${ptcmpEsc(label)}</b></td>${ps.map(p=>`<td>${ptcmpEsc(fn(p))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const cards=ps.map(p=>`<section class="ptcmp-simple-package"><h3>Paket ${p.slot} — ${ptcmpEsc(p.level)}</h3><div class="ptcmp-print-meta">${ptcmpEsc(p.code)} • ${p.sessions} sesi • ${ptcmpEsc(p.validity)}</div>${[['Mode Harga',p.mode],['Harga Paket PT',ptcmpMoney(p.price)],['Harga per Sesi',ptcmpMoney(p.perSession)],['Cashback Automatic PT — Masuk Akun',ptcmpMoney(p.auto)],['Cashback Manual — Potongan Harga',ptcmpMoney(p.manual)],['Harga Setelah Potongan Manual',ptcmpMoney(p.final)],...(p.merch&&p.merch!=='none'?[['Merchandise',p.merch]]:[]),['Manager Approval',p.approval?'✓ Approved':'Belum approved']].map(([l,v])=>`<div class="ptcmp-simple-row"><span>${ptcmpEsc(l)}</span><b>${ptcmpEsc(v)}</b></div>`).join('')}</section>`).join('');root.innerHTML=`<section class="ptcmp-print-page ptcmp-print-page-landscape"><h1>FITNESS JOURNEY</h1><h2>PERSONAL TRAINER COMPARISON</h2><div class="ptcmp-print-meta">Perbandingan ${ps.length} paket PT • ${new Date().toLocaleString('id-ID')}</div><div class="ptcmp-cashback-note"><b>Cashback Automatic PT</b> masuk ke akun dan tidak mengurangi harga. <b>Hanya Cashback Manual</b> yang menjadi potongan harga.</div>${full}</section><section class="ptcmp-print-page ptcmp-print-page-portrait"><h1>FITNESS JOURNEY</h1><h2>PERSONAL TRAINER COMPARISON — RINGKASAN</h2><div class="ptcmp-print-simple-subtitle">Ringkasan tiap paket PT • ${new Date().toLocaleString('id-ID')}</div><div class="ptcmp-cashback-note"><b>Cashback Automatic PT</b> masuk ke akun dan tidak mengurangi harga. <b>Hanya Cashback Manual</b> yang menjadi potongan harga.</div>${cards}</section>`;document.body.appendChild(root);document.documentElement.classList.add('ptcmp-printing');let cleaned=false;const cleanup=()=>{if(cleaned)return;cleaned=true;document.documentElement.classList.remove('ptcmp-printing');root.remove();window.removeEventListener('afterprint',cleanup)};window.addEventListener('afterprint',cleanup);void root.offsetHeight;window.print();setTimeout(cleanup,3000)}
document.addEventListener('DOMContentLoaded',()=>{try{ptcmpBuild()}catch(e){console.error('PT comparison init',e)}});
